# Generated by Django 5.2.12 on 2026-03-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapse_pm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sync Meta',
                'verbose_name_plural': 'Sync Meta',
            },
        ),
    ]
